### ISSUE TITLE
Hardware / connections documentation

### ISSUE THREAD

**Issue by samuk** [adityakamath/akros2_bringup#1]
Hi I'm interested in your project, I have an idea to build a similar open hardware bot, based around [Beaglebone AI-64 ](https://beagleboard.org/ai-64) which is 12cmx 12cm Nano ITX (Ubuntu 22.04 coming later this year) I might try and steal your code for it. 

Thinking to do a PCB base to bolt the motors to & hold some [pluggable I2C sensors](https://shop.pimoroni.com/collections/breakout-garden) :
![base-board](https://user-images.githubusercontent.com/400875/213941178-a1604da9-3f42-4d7e-8266-3167b049ed52.png) Essentially just add a bit of width to the [Smartcar Shield Motor board](https://platis.solutions/blog/2020/02/16/smartcar-gets-an-esp32-upgrade/)

![smart_base](https://user-images.githubusercontent.com/400875/213945055-5bab3e3b-eca1-4a94-9bf6-2536479ee0ab.jpg)

The existing 'modules' ESP32 layer of Smartcar would be replaced with a new layer containing a Teensy. The compute module RPI/ AI-64/ whatever would sit on top of this and connect to the Teensy via USB.

My question is: How are you using your Teensy breakout board? Are you still connecting to your PI/Compute via USB? Your encoder signals are still getting handled by the Teensy?

If I managed to build a bot roughly as above would you be interested in collaborating on it/ getting your code running there?

**Comment by adityakamath** [comment]
Hey! Looks like an interesting project, and I'm certainly open for collaborating :)

I am currently using USB between the Teensy and my RPi, but I have tried using Ethernet and it does work (see this issue for reference: https://github.com/micro-ROS/micro_ros_arduino/issues/1065). I'm only using USB because I couldn't find a neat way to route the Ethernet cable. 😅
